---
name: deploy HTML web into nginx server
on:
  push:
     branches:
           - main  
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: web app deployment
        run: |
          sudo apt-get update
          sudo apt-get install nginx
          sudo service nginx start
          git config --global user.email "sukruth700@gmail.com"
          git config --global user.name "Sukruth"
          git clone https://${{ secrets.TOKEN }}@github.com/sukruth-gms/new-web-index.git
          cd new-web-index
          sudo cp -r assets index.html readme.txt /var/www/html/
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'html-git-action-webapp'  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
