name: CI of the app code using Maven

on:
  workflow_dispatch: null

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Installing Nginx server
        run: |
          sudo apt-get update
          sudo apt-get install nginx
          sudo service nginx start

      - name: App code repository configuration
        run: |
          sudo apt-get update
          sudo apt-get install maven
          mvn --version
          git config --global user.email "sukruth700@gmail.com"
          git config --global user.name "Sukruth" 
          git clone https://${{secrets.TOKEN}}@github.com/Sonal0409/DevOpsClassCodes.git
          cd DevOpsClassCodes
          mvn install
          mvn compile
          mvn test
          mvn package
          mkdir staging && cp target/addressbook.war staging

  publish-job:
    runs-on: ubuntu-latest
    needs: builds
    steps:
      - uses: actions/checkout@v3

      - name: Debugging Output
        run: |
          ls /home/runner/work/test-repo-list-actions/test-repo-list-actions/DevOpsClassCodes/target/

      - name: Artifact Publishing
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: /home/runner/work/test-repo-list-actions/test-repo-list-actions/DevOpsClassCodes/target/
