name: CI of the app code using maven
on:
  workflow_dispatch: null

jobs:
    builds:
       runs-on: ubuntu-latest
       steps:
           - name: Checkout the repository
             uses: actions/checkout@v3
             
           - name: Installing nginx server
             run: |
              sudo apt-get update
              sudo apt-get install nginx
              sudo service nginx start

           - name: App code repository configuration
             run: |
              sudo apt-get update
              sudo apt-get install maven
              mvn --version
              git config --global user.email "sukruth700@gmail.com"
              git config --global user.name "Sukruth"
              git clone https://${{secrets.TOKEN}}@github.com/Sonal0409/DevOpsClassCodes.git
              mvn install
              mvn compile
              mvn test
              mvn package
              cd DevOpsClassCodes
              sudo cp -r DevOpsClassCodes/* /var/www/html/

           - name: Deploying the ecommerce app
             uses: peaceiris/actions-gh-pages@v3
             with:
                 github_token: ${{ secrets.TOKEN }}
                 publish_dir: /var/www/html
                 publish_branch: gh-pages



           
