name: CI of the app code using maven
on:
  workflow_dispatch: null

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Installing nginx server
        run: |
          sudo apt-get update
          sudo apt-get install nginx
          sudo service nginx start

      - name: App code repository configuration
        run: |
          sudo apt-get update
          sudo apt-get install maven
          mvn --version
          git config --global user.email "sukruth700@gmail.com"
          git config --global user.name "Sukruth" 
          git clone https://${{secrets.TOKEN}}@github.com/Sonal0409/DevOpsClassCodes.git
          cd DevOpsClassCodes
          mvn install
          mvn compile
          mvn test
          mvn package

  publish-job:
    runs-on: ubuntu-latest
    needs: builds

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test
        run: mvn --batch-mode --update-snapshots verify

      - name: Create staging directory and copy JAR files
        run: |
          mkdir staging
          cp target/*.jar staging

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
